### ISSUE TITLE
Implement security groups

### ISSUE THREAD

**Issue by trezy** [FuelRats/api.fuelrats.com#25]
We'll implement permissions via adding users to security groups. This will allow us to give administration privileges to the users that need it.

**Comment by dewiniaid** [comment]
Since the bot may eventually be able to do actions on behalf of another user (namely the quick "change ingame name" function, though perhaps attribution of who opened a case as well), should there be a permission allowing a user to perform actions on behalf of another user?

**Comment by xlexi** [comment]
I'd like to flesh out a more detailed overview of what different security groups to implement and what their permissions would be.    

Example:    
   
Normal user: Submit rescues and edit rescues provided by rescues/edit/ link
Moderator: Edit rescues and rats through admin interface.
Admin/Owner: Complete access, even to edit Users password etc.

Please get back to me on this

**Comment by dewiniaid** [comment]
I was planning on adding something similar in Mecha, since the current channel-mode-based access model was only intended to be temporary for a lot of cases.

My thought is: 
- Set of privileges
- Some privileges implicitly grant other privileges.  We can call these "roles"
- Access checks primarily use checks for individual privileges.  User grants primarily grant one or more roles

So, granting someone admin implies things like reset_password, delete_rat, etc.  We'd rarely grant individual privileges (though it might be something we do for special cases), but it we need a new privilege down the line we can add it and change the implicit  grants for the roles where it makes sense.

If we want, we can add a second set for explicitly denied privileges and use the common ACL strategy of explicit deny > implicit or explicit allow > default deny.

Depending on the granularity, this can handle my desire for Mecha to have limited impersonation abilities: give it the ability to become the account in question but with a drastically reduced privilege set.

**Comment by xlexi** [comment]
While I'd enjoy such a granular permission system I don't know if it would be a bit overly complex for these purposes. But I'm open to it. I'd like @trezy and @kenneaal to chime in on this as well

**Comment by xlexi** [comment]
I have dealt with this kind of system before and have a good idea of how to implement it, the most time consuming part would be creating all the UX for creating roles, assigning roles, assigning permissions to roles, assigning permission to users without roles..

**Comment by kenneaal** [comment]
I have to agree with Xlexi on this; we don't need that kind of granularity for the API. We get enough granularity from using an enum with room between the ints to fit in more roles if we end up needing them, and leaving permission checks a simple "greater than X privilege".

**Comment by trezy** [comment]
Yeah, I don't see any need for the granularity. The four permission groups mentioned previously -- user, overseer, moderator, and admin -- are plenty for what we need now.

**Comment by xlexi** [comment]
Alright, settled for now then.

__Normal/Rat:__ Submit rescues, Edit rescues where they are an assigned rat    
__Overseer:__ Create rat, edit rats, all drill related permissions
__Moderator:__ Create, edit all rescues, and delete rescues
__Admin:__ All permissions
