### ISSUE TITLE
Create i18n endpoint

### ISSUE THREAD

**Issue by trezy** [FuelRats/api.fuelrats.com#36]
We need to add an endpoint to support i18n for all of our product offerings. The syntax should be something like this: `/i18n/:languageCode/:key`

**`GET /i18n/de/save`**
```json
{
  "links": { ... },
  "data": {
    "save": "sparen"
  }
}
```

**or**

**`GET /i18n/de`**

```json
{
  "links": { ... },
  "data": {
    "delete": "löschen",
    "goodbye": "auf wiedersehen",
    "hello": "hallo",
    "needFuel": "ich brauche brennstoff",
    "save": "sparen"
  }
}
```

**Comment by dewiniaid** [comment]
Having implemented FuelRats/pipsqueak#49, I'd like to add some feedback to this:

- This may need some categorization.  Some interfaces won't need text for standard UI things like Save/Delete/Edit.  Some interfaces will be from a rat-centric point of view and won't need things like the Facts database.  (Actually, UI localization might happen at build time, with something that pulls the translation table)  This also means we can have a category for app-specific phrases for each app, a category for common UI, and a category for client communication/etc.

- The interim Mecha2 implementation supports requesting a fact in a list of languages and quietly falling back to the first available translation.  If the API format supports sending a list of language codes in order, that can be done in the first request.  This aids usability when full translations are not available -- someone who prefers German but can read English would probably prefer the English text to no version at all.

- i18n phrases may need embedded parameters.  "Case #{id} for {client} closed." and the like.  We should standardize on a format for said parameters (I like the above because Python), though the names can vary on a case-by-case basis.

- Mecha's facts can include IRC formatting.  Some instances may want text.  Some may want HTML.  I suggest a subset of HTML (perhaps bold/italic/underline) as the native format with an option to request text-only versions of translations.  If we do this, I'll write the IRC-to-HTML translation layer on Mecha's end.

- Mecha's interim implementation has fact, lang, message and (optional) author fields currently.  lastModified fields can be useful too.  It's also written in such a way where the API can be dropped in mostly by updating the interface class to make API calls instead of database queries.

**Comment by xlexi** [comment]
@trezy please explain the original meaning of this issue and whether it is still relevant, or should be moved to FuelRats/fuelrats.com

**Comment by trezy** [comment]
The original purpose behind this ticket was manyfold:

1. Provide internationalization for the website and all of our other offerings
1. Maintain standard verbiage across all of our offerings

Rather than using their own, arbitrary strings and translations, products would utilize our i18n endpoints for the they strings use. For example, when dispatch uses the `!pcwing-de` command, Mechasqueak would make request to the API to get the correct string before printing it.

The original motivations behind this issue evade me, but I believe that the advantage of maintaining dynamic strings throughout our applications is reason enough to implement it.

**Comment by xlexi** [comment]
I do not believe mecha making HTTP requests for facts is very sensible and further diminishes its ability to function during downtime, with little benefit as the facts used by mecha would virtually never be useful on the website, and vise versa.   
   
Unless you have any objections I would like to move this issue to fuelrats/fuelrats.com as that is where internationalisation would be most relevant

**Comment by trezy** [comment]
Sure, go for it. We can come back to it when it matters. :-)

**Comment by xlexi** [comment]
Cool :)

**Comment by xlexi** [comment]
Moved to FuelRats/fuelrats.com#5
