### ISSUE TITLE
Should we replace IRC nicknames/etc with something like URIs?

### ISSUE THREAD

**Issue by dewiniaid** [FuelRats/api.fuelrats.com#41]
As a way of adding support for other communications methods in the future without needing to extend the protocol, should we replace the current bits of the API that reference nicknames to use a set of URIs instead?

For instance, a client's handle might be be `irc://network-identifier/nick` or `discord://server/name` or `skype://name`  or `reddit://username` (Not certain on the exact format, but trying to get the idea across).  

Grouped nicks when the IRC integration comes would then be a set of irc:// URLs associated with the rat, in addition to whatever other services they use.

**Comment by trezy** [comment]
I'd prefer we do this with separate fields. If we add support for these other platforms then we should extend the API to handle them properly, for example:

```json
{
  CMDRname: '...',
  platform: '...',
  nicknames: [...], // IRC nicknames
  reddit: {
    email: '...',
    hash: '...',
    username: '...'
  },
  discord: {
    email: '...',
    hash: '...',
    username: '...'
  }
}
```

I added the hash to these fields because we can also support things like logging in with those accounts via PassportJS which is already being utilized for login.
