### ISSUE TITLE
Safe partial modification of nested fields (e.g. rats, quotes, etc.)

### ISSUE THREAD

**Issue by dewiniaid** [FuelRats/api.fuelrats.com#45]
Currently, if two clients simultaneously modify a rescue's `quotes` field, the changes of the first client will be overridden by the second.  This is less than ideal if both clients are adding a new quote.  This also looks like it happens for rats and tempRats, among other cases.

For quotes, there are two common actions I can see being useful:
- API call to replace or delete selected quote(s), leaving others untouched.  (Needs a reliable way to identify quotes -- e.g. the id field in #44)   (Bot equivalent of `!sub`)
- API call to append quote(s) to the existing list.

For rats/tempRats:
- API call with list of rats to add or remove. (I'm assuming this is a set-like object behind the scenes -- in any case, there should be no error in removing a rat who's not in the list and no duplication adding a rat that's already on the list.)

**Comment by trezy** [comment]
The fix for this will be #24. Once versioning is reimplemented version numbers will be required with every request. If two clients try to modify a resource at the same time one of them will receive a success response for sending the correct version number, while the other receives an error because their version is now out of date.
