### ISSUE TITLE
Transition user credentials to bcrypt

### ISSUE THREAD

**Issue by xlexi** [FuelRats/api.fuelrats.com#76]

**Comment by trezy** [comment]
I used PassportJS and passport-local-mongoose to make it stupid easy to hook in the local authentication. It wouldn't be that hard to rip out passport-local-mongoose and replace it with whatever encryption method we want. However, we're not a bank. I think the current password hashing is fine.

**Comment by dewiniaid** [comment]
I'm the one who originally raised this, and here's why:

No, we're not a bank.  However, there's probably at least one rat who uses the same password and mail address/account name everywhere.  In the event that our site is someone compromised (unlikely due to being fully custom and a small target, but not impossible) we should take measures to try to protect our users' information.

Modern GPUs can compute md5/sha-based hashes at alarmingly high speeds: see the performance metrics at http://hashcat.net/oclhashcat/ .  That's in part because these functions are designed to as fast as possible -- they're intended to ensure data was not altered in transmission, not to secure a password.

bcrypt, scrypt and pbkdf2, on the other hand, are designed to be slow and resource intensive.  For us, it's not that noticeable of a slowdown because users aren't logging in that often. For an attacker who is attempting to brute force passwords millions of times faster than the rate we handle logins and who is using a GPU which is limited in overall memory and relatively poor at certain types of branching instructions the difference is quite significant.

I know from talking to Alex that our existing library supports pbkdf2 at least, so we should at least switch to that.  For existing users, we can convert their password to the new format next time they log in and perhaps do rolling password resets a month or two from now for the remaining sha users.

**Comment by kenneaal** [comment]
This isn't really about whether it is feasible to change password hashing algorithms, or whether we should settle for mostly secure. It's a question about where we are currently expending our efforts. Right now, we're looking at March coming up fast, and we're STILL not ready to release anything. Our efforts at this point should be focused on one thing. Getting the API production ready, getting Mecha production ready, and getting RT production ready. We don't get there by reiterating on what's already working.

We can look at this later, but now is not the time, IMO.

**Comment by dewiniaid** [comment]
One could argue that the presence of known security issues would indicate that something is not production ready.

I mentioned pbkdf2 because the amount of work required to make that change is drastically less than the work required for bcrypt and thus wouldn't push release back nearly as much.  In fact, if someone points me at the relevant parts of the code... I might finally have a reason to have a development copy of the API.

(I have enough to do, but this matters to me.)

**Comment by xlexi** [comment]
bcrypt transition will now occur automatically during the transition to postgres as people login
